tmdbApi:
  apiKey: ${TMDB_API_KEY}

apiLinks:
  top-rated-movies-uri: https://api.themoviedb.org/3/movie/top_rated?api_key={apiKey}&language=en-US&page=1&region=DE
  latest-movies-uri: https://api.themoviedb.org/3/movie/now_playing?api_key={apiKey}&language=en-US&page=1&region=DE
  most-popular-movies-uri: https://api.themoviedb.org/3/movie/popular?api_key={apiKey}&language=en-US&page=1&region=DE
  upcoming-movies-uri: https://api.themoviedb.org/3/movie/upcoming?api_key={apiKey}&language=en-US&page=1&region=DE

  top-rated-tv-uri: https://api.themoviedb.org/3/tv/top_rated?api_key={apiKey}&language=en-US&page=1&region=DE
  latest-tv-uri: https://api.themoviedb.org/3/tv/latest?api_key={apiKey}&language=en-US&page=1&region=DE
  most-popular-tv-uri: https://api.themoviedb.org/3/tv/popular?api_key={apiKey}&language=en-US&page=1&region=DE
