api:
  api-context:
    key: ${TMDB_API_KEY}
    movies:
      top-rated: https://api.themoviedb.org/3/movie/top_rated?api_key={apiKey}&language=en-US&page=1&region=DE
      latest: https://api.themoviedb.org/3/movie/now_playing?api_key={apiKey}&language=en-US&page=1&region=DE
      most-popular: https://api.themoviedb.org/3/movie/popular?api_key={apiKey}&language=en-US&page=1&region=DE
      upcoming: https://api.themoviedb.org/3/movie/upcoming?api_key={apiKey}&language=en-US&page=1&region=DE
    tv:
      top-rated: https://api.themoviedb.org/3/tv/top_rated?api_key={apiKey}&language=en-US&page=1&region=DE
      latest: https://api.themoviedb.org/3/tv/latest?api_key={apiKey}&language=en-US&page=1&region=DE
      most-popular: https://api.themoviedb.org/3/tv/popular?api_key={apiKey}&language=en-US&page=1&region=DE
